# Generated by Django 3.2.6 on 2021-08-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_category', '0001_initial'),
        ('cms_posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='active',
            field=models.BooleanField(default=False, verbose_name='فعال / غیرفعال'),
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, to='cms_category.PostCategory', verbose_name='دسته بندی ها'),
        ),
    ]
