# Generated by Django 3.2.6 on 2021-08-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_posts', '0003_auto_20210830_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.TimeField(null=True, verbose_name='زمان'),
        ),
    ]
