# Generated by Django 3.2.6 on 2021-09-01 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_posts', '0004_post_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on'], 'verbose_name': 'پست', 'verbose_name_plural': 'پست ها'},
        ),
    ]
