# Generated by Django 3.2.6 on 2021-09-02 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_posts', '0005_alter_post_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
