# Generated by Django 3.2.6 on 2021-09-13 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_posts', '0006_post_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='thumbnail',
        ),
    ]
