# Generated by Django 3.2.6 on 2021-09-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_posts', '0006_remove_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='slug', max_length=200, verbose_name='عنوان در url'),
        ),
    ]
