# Generated by Django 3.2.6 on 2021-09-07 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_posts', '0010_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='time',
        ),
    ]
