# Generated by Django 3.2.6 on 2021-09-07 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_tags', '0002_delete_tag'),
        ('cms_posts', '0012_auto_20210907_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='PostCategory',
        ),
    ]
