# Generated by Django 3.2.6 on 2021-09-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_contact', '0002_alter_contactus_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='text',
            field=models.TextField(verbose_name='متن پیام'),
        ),
    ]
