# Generated by Django 3.2.6 on 2021-09-01 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
    ]
