# Generated by Django 3.2.6 on 2021-09-03 18:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_posts', '0008_alter_post_slug'),
        ('cms_comments', '0003_auto_20210903_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='blogpost_connected',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cms_posts.post', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_posted',
            field=django_jalali.db.models.jDateField(default=django.utils.timezone.now, null=True, verbose_name='تاریخ'),
        ),
    ]
