# Generated by Django 3.2.6 on 2021-09-03 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_posts', '0008_alter_post_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms_comments', '0004_auto_20210903_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='blogpost_connected',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cms_posts.post', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_posted',
            field=django_jalali.db.models.jDateField(default=django.utils.timezone.now, verbose_name='تاریخ'),
        ),
    ]
