# Generated by Django 3.2.6 on 2021-09-04 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'پروفایل کاربر', 'verbose_name_plural': 'پروفایل کاربران'},
        ),
    ]
