# Generated by Django 3.2.6 on 2021-09-05 21:06

import cms_account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_account', '0004_auto_20210905_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=cms_account.models.upload_image_path, verbose_name='آواتار'),
        ),
    ]
