# Generated by Django 3.2.6 on 2021-09-06 15:03

import cms_account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_account', '0007_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=cms_account.models.upload_image_path, verbose_name='آواتار'),
        ),
    ]
