# Generated by Django 3.2.6 on 2021-09-07 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_category', '0002_postcategory_on_home'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostCategory',
        ),
    ]
