# Generated by Django 3.2.6 on 2021-09-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('email_use_tls', models.BooleanField(default=True, verbose_name='EMAIL_USE_TLS')),
                ('email_use_ssl', models.BooleanField(default=False, verbose_name='EMAIL_USE_SSL')),
                ('email_ssl_keyfile', models.CharField(blank=True, max_length=1024, null=True, verbose_name='EMAIL_SSL_KEYFILE')),
                ('email_ssl_certfile', models.CharField(blank=True, max_length=1024, null=True, verbose_name='EMAIL_SSL_CERTFILE')),
                ('email_host', models.CharField(max_length=1024, verbose_name='EMAIL_HOST')),
                ('email_host_user', models.CharField(max_length=255, verbose_name='EMAIL_HOST_USER')),
                ('email_host_password', models.CharField(max_length=255, verbose_name='EMAIL_HOST_PASSWORD')),
                ('email_port', models.PositiveSmallIntegerField(default=587, verbose_name='EMAIL_PORT')),
                ('email_timeout', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='EMAIL_TIMEOUT')),
                ('active', models.BooleanField(default=False, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'تنظیم mail',
                'verbose_name_plural': 'تنظیمات mail',
            },
        ),
    ]
