# Generated by Django 3.2.6 on 2021-09-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_contact', '0002_newslettersignup'),
        ('cms_mail', '0002_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='to',
        ),
        migrations.AddField(
            model_name='mail',
            name='to',
            field=models.ManyToManyField(max_length=254, to='cms_contact.NewsletterSignUp', verbose_name='ارسال به'),
        ),
    ]
