# Generated by Django 3.2.6 on 2021-09-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_mail', '0003_auto_20210917_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='to',
            new_name='receiver',
        ),
        migrations.AlterField(
            model_name='mail',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'sent'), (1, 'failed'), (2, 'queued')], db_index=True, default=2, null=True, verbose_name='Status'),
        ),
    ]
