# Generated by Django 3.2.6 on 2021-09-17 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_mail', '0004_auto_20210917_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='send_now',
        ),
    ]
