# Generated by Django 3.2.6 on 2021-09-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_mail', '0006_mail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='emails/', verbose_name='عکس(اختیاری)'),
        ),
    ]
