# Generated by Django 3.2.6 on 2021-09-07 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_tags', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
