# Generated by Django 3.2.6 on 2021-09-07 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_tags', '0003_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
